name: baristodolistapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  great_list_view: ^0.2.3
  synchronized: ^3.1.0
  build_runner: ^2.4.6
  dartz: ^0.10.1
  mockito: ^5.4.2
  auto_size_text: ^3.0.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  http: ^1.1.0
  get: ^4.6.5
  connectivity_plus: ^5.0.0
  dio: ^5.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/todolistLogo3.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  fonts:
    - family: Handlee
      fonts:
        - asset: assets/Handlee-Regular.ttf
  # To add assets to your application, add an assets section, like this:
  assets:
    
    - assets/blue_checkmark.svg         #https://pixabay.com/de/vectors/checkbox-h%c3%a4kchen-markierung-pr%c3%bcfen-303113/
    - assets/blueBug.svg                #https://pixabay.com/de/vectors/k%c3%a4fer-insekt-tier-k%c3%a4fer-insekt-34372/
    - assets/nullenUndEinsen.jpg        #https://pixabay.com/de/illustrations/digital-null-eins-informatik-484402/
    - assets/tabby-cat-6788375_1920.jpg #https://pixabay.com/de/photos/tabby-katze-schlafende-katze-bett-6788375/
    - assets/woman_stretching.jpg       #https://pixabay.com/de/photos/frau-fitness-fit-leben-gesund-1456950/
    - assets/todo_list_image.jpg        #https://pixabay.com/de/photos/todo-listen-aufgaben-aufgabenliste-5238324/
    - assets/library.jpg                #https://pixabay.com/de/photos/bibliothek-b%c3%bccher-wissen-historisch-419254/
    - assets/paprika_orange.jpg         #https://pixabay.com/de/photos/paprika-salat-sellerie-n%c3%bcsse-3212137/
    - assets/desk_computer.jpg          #https://pixabay.com/de/photos/sch%c3%bcler-tippen-klaviatur-text-849825/
    - assets/shopping.jpg               #https://pixabay.com/de/photos/frau-einkaufen-lebensstil-3040029/
    - assets/pills.jpg                  #https://pixabay.com/de/photos/medikamente-tablets-medizin-heilung-1853400/
    - assets/puppy.jpg                  #https://pixabay.com/de/photos/hund-welpe-hundebaby-4372036/
    - assets/meditation.jpg             #https://pixabay.com/de/photos/yoga-frau-see-drau%c3%9fen-lotus-pose-2176668/
    - assets/cleanup.jpg                #https://pixabay.com/de/photos/desinfektionsmittel-spr%c3%bchen-abzug-5093503/
    - assets/folder.jpg                 #https://pixabay.com/de/photos/mappe-ordner-b%c3%bcro-papierkram-4119674/
    - assets/drinks.jpg                 #https://pixabay.com/de/photos/getr%c3%a4nke-alkohol-cocktails-2578446/
    - assets/todolistLogo3.png
    - assets/hakendran_loginpage.png


    #- images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
