// Mocks generated by Mockito 5.1.0 from annotations
// in baristodolistapp/test/domain/usecases/all_todolists_usecases_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:baristodolistapp/domain/entities/todolist_entity.dart' as _i6;
import 'package:baristodolistapp/domain/failures/failures.dart' as _i5;
import 'package:baristodolistapp/domain/repositories/allTodolists_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [AllTodoListsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllTodoListsRepository extends _i1.Mock
    implements _i3.AllTodoListsRepository {
  MockAllTodoListsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> createNewTodoList(
          {_i6.TodoListEntity? todoListEntity}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createNewTodoList, [], {#todoListEntity: todoListEntity}),
              returnValue: Future<_i2.Either<_i5.Failure, int>>.value(
                  _FakeEither_0<_i5.Failure, int>()))
          as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
