name: TEST FLUTTER APP
on: [workflow_dispatch, push]
  
env:
  FLUTTER_VERSION: "3.16.4"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Get Packages
        run: flutter pub get
      - name: 'Create env file'
        run: |
          touch .env
          echo BACKENDBASEURL=${{ secrets.BACKENDBASEURL }} >> .env
          cat .env  
      - name: Run Tests
        run: flutter test --no-pub